### ISSUE TITLE
People/Characters API

### ISSUE THREAD

**Issue by ghost** [KatsuteDev/Mal4J#398]
The MyAnimeList API will, at some point, add a characters and people API. See https://myanimelist.net/forum/?topicid=1973141&show=0#msg64959633

> However, the API cannot be used (yet) to:
> - post comments in the forum²;
> - send private messages to other users²;
> - **query the characters or people databases³;**
> - access the news or featured articles pages;
> - interact with several other functionalities found on the website.
>
> (¹) Only the main forum boards can be accessed.
> (²) It's technically possible to send messages and post forum comments using the API, but the recent introduction of Google reCAPTCHA made it impossible to perform such actions in an automated manner.
> **(³) The characters and people endpoints exist but are undocumented and under active development. Don't use them.**

**Comment by Katsute** [comment]
@kdevbot issue People/Characters API
